// Generated by src/scripts/csv_to_dtc_table.py from src/data/Mustang_DTC.csv. Do not edit by hand - re-run the script instead.
#pragma once

#include <stddef.h>

struct DtcDefinition {
    const char* code;
    const char* description;
};

// Sorted by code (strcmp order) so lookupDtcDescription() (src/system/dtc_lookup.h) can binary-search it.
extern const DtcDefinition kDtcTable[];
extern const size_t kDtcTableCount;
