; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:cyd_4inch]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv

monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43

build_flags =
    -D USER_SETUP_LOADED
    -D ST7796_DRIVER
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=27
    -D TOUCH_CS=33
    -D SPI_FREQUENCY=20000000
    -D SPI_READ_FREQUENCY=10000000
    -D SPI_TOUCH_FREQUENCY=2500000
    -D BOOT_IMAGE_MODE=0
    -D BOOT_RGB666_ASSETS_AVAILABLE=1
    -D SD_LOGGING_ENABLED

; To bench-test without an SD card inserted, comment out the SD_LOGGING_ENABLED
; flag above (or remove the line) and rebuild.
