#!/usr/bin/env python3
"""Convert a DTC code/description CSV into a flash-resident C++ table.

Companion to png_to_header.py in this same directory (src/scripts/): same
"convert a source asset into checked-in generated source" convention, but for
tabular text data instead of binary bytes. Uses Python's csv module so quoted
fields, embedded commas, and doubled "" (escaped quotes) in the description
column are all handled correctly - no CSV parsing is needed on the device.

Emits <out-dir>/dtc_table.h (extern declarations) and dtc_table.cpp (the
generated const array, sorted by code so the device can binary-search it),
matching the struct-table style already used by src/obd/obd_pids.cpp.

Usage:
    python csv_to_dtc_table.py <input.csv> -o src/system
"""
import argparse
import csv
import sys


def read_rows(path: str):
    with open(path, encoding="utf-8-sig", newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        if len(header) < 2:
            raise ValueError(f"expected at least 2 columns, got header {header!r}")

        rows = []
        for line_num, row in enumerate(reader, start=2):
            if not row or (len(row) == 1 and not row[0].strip()):
                continue
            if len(row) != 2:
                raise ValueError(f"line {line_num}: expected 2 columns, got {row!r}")
            code, description = row[0].strip(), row[1].strip()
            if not code:
                raise ValueError(f"line {line_num}: empty code")
            rows.append((code, description))
        return rows


def escape_c_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def write_header(out_path: str):
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(
            "// Generated by src/scripts/csv_to_dtc_table.py from "
            "src/data/Mustang_DTC.csv. Do not edit by hand - re-run the "
            "script instead.\n"
            "#pragma once\n\n"
            "#include <stddef.h>\n\n"
            "struct DtcDefinition {\n"
            "    const char* code;\n"
            "    const char* description;\n"
            "};\n\n"
            "// Sorted by code (strcmp order) so lookupDtcDescription() "
            "(src/system/dtc_lookup.h) can binary-search it.\n"
            "extern const DtcDefinition kDtcTable[];\n"
            "extern const size_t kDtcTableCount;\n"
        )


def write_source(out_path: str, rows):
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(
            "// Generated by src/scripts/csv_to_dtc_table.py from "
            "src/data/Mustang_DTC.csv. Do not edit by hand - re-run the "
            "script instead.\n"
            '#include "system/dtc_table.h"\n\n'
            "const DtcDefinition kDtcTable[] = {\n"
        )
        for code, description in rows:
            f.write(
                f'    {{"{escape_c_string(code)}", '
                f'"{escape_c_string(description)}"}},\n'
            )
        f.write("};\n\n")
        f.write(
            "const size_t kDtcTableCount = "
            "sizeof(kDtcTable) / sizeof(kDtcTable[0]);\n"
        )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_csv", help="Path to the DTC code/description CSV")
    parser.add_argument(
        "-o", "--out-dir", required=True, help="Directory to write dtc_table.h/.cpp into"
    )
    args = parser.parse_args()

    rows = read_rows(args.input_csv)

    seen = {}
    for code, description in rows:
        if code in seen and seen[code] != description:
            print(
                f"warning: duplicate code {code!r} with differing descriptions "
                f"({seen[code]!r} vs {description!r}); keeping first",
                file=sys.stderr,
            )
        seen.setdefault(code, description)
    deduped = sorted(seen.items())

    write_header(f"{args.out_dir}/dtc_table.h")
    write_source(f"{args.out_dir}/dtc_table.cpp", deduped)
    print(f"Wrote {len(deduped)} DTC entries ({len(rows) - len(deduped)} duplicate codes dropped)")


if __name__ == "__main__":
    main()
