#!/usr/bin/env python3
"""Embed a PNG file's raw bytes as a PROGMEM C array header.

Generic byte-embedding only - no pixel/palette logic. Reads the PNG
signature and IHDR chunk directly (no Pillow dependency) to describe the
asset in the generated comment, and reproduces the exact formatting used by
the existing src/assets/boot_logo_png.h: uppercase 0xNN hex bytes, 20 per
line, 4-space indent, a trailing comma after every byte including the last.

Companion to optimize_png.py in this same directory (src/scripts/).

Usage:
    python png_to_header.py <input.png> -o <output.h> --name boot_logo
"""
import argparse
import struct
import sys

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
BYTES_PER_LINE = 20

COLOR_TYPE_NAMES = {
    0: "grayscale",
    2: "truecolor (RGB)",
    3: "indexed-color",
    4: "grayscale with alpha",
    6: "truecolor with alpha",
}


def read_ihdr(data: bytes):
    if data[:8] != PNG_SIGNATURE:
        raise ValueError("not a PNG file (bad signature)")
    # IEND chunk is 12 bytes total: 4-byte length(0) + "IEND" + 4-byte CRC.
    if data[-8:-4] != b"IEND":
        raise ValueError("not a valid PNG file (missing trailing IEND chunk)")

    length = struct.unpack(">I", data[8:12])[0]
    chunk_type = data[12:16]
    if chunk_type != b"IHDR" or length != 13:
        raise ValueError("not a valid PNG file (missing leading IHDR chunk)")

    width, height, bit_depth, color_type = struct.unpack(">IIBB", data[16:26])
    return width, height, bit_depth, color_type


def to_pascal_case(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_") if part)


def format_array(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        line = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {line},")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", help="Source PNG path")
    parser.add_argument("-o", "--output", required=True, help="Generated header output path")
    parser.add_argument("--name", required=True, help="Asset name, e.g. boot_logo -> kBootLogoPng")
    args = parser.parse_args()

    with open(args.input, "rb") as f:
        data = f.read()

    try:
        width, height, bit_depth, color_type = read_ihdr(data)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    color_type_name = COLOR_TYPE_NAMES.get(color_type, f"unknown (type {color_type})")
    article = "an" if color_type_name[0] in "aeiou" else "a"
    pascal_name = to_pascal_case(args.name)
    array_name = f"k{pascal_name}Png"
    size_name = f"k{pascal_name}PngSize"
    raw_rgb565_bytes = width * height * 2

    header = f"""#pragma once

#include <stdint.h>
#include <pgmspace.h>

// {args.name.replace('_', ' ').title()}, stored as {article} {color_type_name} PNG
// ({width}x{height}, {bit_depth}-bit) and decoded at boot via PNGdec (see
// DisplayManager::drawBootImage()). {len(data)} bytes here vs. {raw_rgb565_bytes}
// bytes for the equivalent raw RGB565 array.
// Generated by src/scripts/optimize_png.py + png_to_header.py from {args.input}.
constexpr uint32_t {size_name} = {len(data)};
const uint8_t {array_name}[] PROGMEM = {{
{format_array(data)}
}};
"""

    with open(args.output, "w", newline="\n") as f:
        f.write(header)

    print(f"wrote {args.output} ({len(data)} bytes, {array_name}/{size_name})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
